include: package:flutter_lints/flutter.yaml

# https://dart.dev/guides/language/analysis-options
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - 'lib/generated/**'
