version: 2
updates:
  # pub updates (plugin)
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily

  # gradle updates (plugin)
  - package-ecosystem: gradle
    directory: android
    schedule:
      interval: daily

  # pub updates (example app)
  - package-ecosystem: pub
    directory: example
    schedule:
      interval: daily

  # gradle updates (example app)
  - package-ecosystem: gradle
    directory: example/android
    schedule:
      interval: daily
