name: flutter_native_barcode_scanner
description: A barcode scanner for Flutter, using platform native APIs.
version: 0.4.7
homepage: https://cloudacy.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: '>=1.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: io.cloudacy.flutter_native_barcode_scanner
        pluginClass: FlutterNativeBarcodeScannerPlugin
      ios:
        pluginClass: FlutterNativeBarcodeScannerPlugin
