name: flutter_native_barcode_scanner
description: A barcode scanner for Flutter, using platform native APIs.
version: 0.6.0
homepage: https://github.com/cloudacy/flutter_native_barcode_scanner

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: '>=2.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: io.cloudacy.flutter_native_barcode_scanner
        pluginClass: FlutterNativeBarcodeScannerPlugin
      ios:
        pluginClass: FlutterNativeBarcodeScannerPlugin
